name: Remove environment
#permissions: read-all
on:
  pull_request_target:
    types: [opened, synchronize, closed]
  workflow_dispatch:
    inputs:
      prNumber:
        required: true
        type: string
        description: Choose which PR number to destroy
jobs:
  test:
    if: ${{ github.event.inputs.prNumber || github.event.pull_request.head.repo.full_name == 'marot/test-workflows' }}
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: switching from HTTPS to SSH
        run: |
          git config --global user.name 'Marco Rotili'
          git config --global user.email 'marot@users.noreply.github.com'
          git remote set-url --push origin https://marot:${{ secrets.GITHUB_TOKEN }}@github.com/marot/test-workflows
      - name: Update file
        run: echo ${{ github.event.pull_request.head.ref }} >> ref
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Auto updating TODO.txt"
      - name: fetch from master
        run: git fetch origin master
      - name: push code to master
        run: git push origin HEAD:master
